"""change model

Revision ID: 0c17a456972f
Revises: 4d8ac5b22805
Create Date: 2025-07-05 00:28:32.241667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c17a456972f'
down_revision = '4d8ac5b22805'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activate', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # Optionally, remove server_default if you don’t want future inserts to default to False:
    op.alter_column('user', 'activate', server_default=None)
    op.alter_column('user', 'deleted', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('activate')

    # ### end Alembic commands ###
