"""add email_verified

Revision ID: 4d8ac5b22805
Revises: 4512e9d12503
Create Date: 2025-07-03 13:30:03.641991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8ac5b22805'
down_revision = '4512e9d12503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['reviewed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('evidence_urls', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assigned_admin_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['assigned_admin_id'], ['id'])
        batch_op.drop_column('reason')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('otp_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('password_created_at', sa.DateTime(), nullable=False, server_default=sa.text("'1970-01-01 00:00:00'")))
        batch_op.add_column(sa.Column('password_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_change_required', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email_verification_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('password_change_required')
        batch_op.drop_column('password_expires_at')
        batch_op.drop_column('password_created_at')
        batch_op.drop_column('otp_attempts')
        batch_op.drop_column('otp_expires')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email_verification_token_expires')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('assigned_admin_id')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('resolution')
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('severity')
        batch_op.drop_column('evidence_urls')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('report_type')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)

    op.drop_table('rating')
    op.drop_table('password_history')
    # ### end Alembic commands ###
