"""Add pending_role to User

Revision ID: 7fd1d3e463c7
Revises: 0dbb5237a4ed
Create Date: 2025-07-06 07:56:38.514144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd1d3e463c7'
down_revision = '0dbb5237a4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2000),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_role', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pending_role')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    op.drop_table('audit_log')
    # ### end Alembic commands ###
