#!/bin/bash

# This script persists environment variables to a file
# It's useful for CI/CD deployments that might overwrite .env files

# Directory where we'll store persisted environment variables
PERSIST_DIR="/app/persistent"
PERSIST_FILE="${PERSIST_DIR}/env.sh"

# Create directory if it doesn't exist
mkdir -p "${PERSIST_DIR}"

# Function to save an environment variable
save_var() {
  local var_name=$1
  local var_value=${!var_name}
  
  # Only save non-empty variables
  if [ ! -z "${var_value}" ]; then
    echo "export ${var_name}='${var_value}'" >> "${PERSIST_FILE}"
    echo "✅ Saved ${var_name} to persistent storage"
  fi
}

# Create or truncate the file
echo "# Persisted environment variables - $(date)" > "${PERSIST_FILE}"
echo "# DO NOT EDIT THIS FILE MANUALLY" >> "${PERSIST_FILE}"
echo "" >> "${PERSIST_FILE}"

# Save all important environment variables
save_var "FLASK_SECRET_KEY"
save_var "CSRF_SECRET_KEY"
save_var "DATABASE_PASSWORD"
save_var "DATABASE_USERNAME"
save_var "DATABASE_NAME"
save_var "AWS_ACCESS_KEY_ID"
save_var "AWS_SECRET_ACCESS_KEY"
save_var "AWS_REGION"
save_var "S3_BUCKET_NAME"
save_var "SES_SENDER_EMAIL"
save_var "SITEKEY"
save_var "RECAPTCHA_SECRET_KEY"

# Make the file executable
chmod +x "${PERSIST_FILE}"

echo "Environment variables persisted to ${PERSIST_FILE}"
