name: OWASP Dependency Check

on: [ push, pull_request ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js (for frontend or tooling)
        uses: actions/setup-node@v4
        with:
          node-version: '20'  

      - name: Install Node dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements-prod.txt

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "safe-companions"
          path: "."
          format: "HTML"
          out: 'dependency-check-report'
          args: >
            --enableExperimental
            --scan requirements-prod.txt

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: dependency-check-report
